alias kido="cd /home/rmongia/kido"
alias bin="cd $HOME/kido/build"
alias cf="find . -iname \"*.c\" -o -iname \"*.cpp\" -o -iname \"*.h\" -o -iname \"*.hpp\" > cscope.files"
alias cs='cscope -b -i cscope.files -f cscope.out'
alias tagify="ctags -L cscope.files"
alias mj="make -j 8 -l 4"
alias dmj="make -j 40"
alias nmrestart="pkill nm-applet && nohup nm-applet &"
alias vpnstop="sudo service openvpn stop"
alias vpnstart="sudo service openvpn start"
alias cp=gcp
alias d="ssh rmongia-desktop"
alias pmj="distcc-pump make -j5"
alias vg="/usr/bin/valgrind --leak-check=no --show-reachable=no --workaround-gcc296-bugs=yes --num-callers=50 --suppressions=/home/rmongia/kido/cmake/instart.supp"
alias gg="git grep"
